[[HelloWorldRust]]
arch = "aarch64"
git-tree-sha1 = "5f9b0374bcc75a22e6efaf37a688251a600c2404"
os = "macos"

    [[HelloWorldRust.download]]
    sha256 = "1c1dd02816901687823d236518541639a6868edf057e722d95bf76da79731bb0"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.aarch64-apple-darwin.tar.gz"
[[HelloWorldRust]]
arch = "aarch64"
git-tree-sha1 = "36140eb82dee89f20eb39583d73bb5b0c934cd14"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "c9babad1ccff03e42e083e13db9473f4dad57e9f68d984f4ff1e855ed5f45993"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.aarch64-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "aarch64"
git-tree-sha1 = "3be15d594770746cb51518481d682f8d680b81cd"
libc = "musl"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "2a6f6eb08da683297132bd043501435379253b565c54649732a28e6667dbd830"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.aarch64-linux-musl.tar.gz"
[[HelloWorldRust]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "330334a573dce29c4adcfbf037b0cdda9cdff176"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "1a6eede04d9cbaa0eb65daf24d8dcd53b4567eafea911bd0d94563078d62bd5f"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.armv6l-linux-gnueabihf.tar.gz"
[[HelloWorldRust]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "721e15c3456dc181ecd68682dca7e656ae3c87cd"
libc = "musl"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "30a6a64516bce52065b4f9d37e2e950fb3402a75ddf918c133081553aae237a2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.armv6l-linux-musleabihf.tar.gz"
[[HelloWorldRust]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9c726478bb1730b1bcc42f71ad59104272a6c5f"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "290c1bbea75d37e69d42c5c5bf44cc2c47cf6d118cbb3fde5e5c61ae800857c8"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[HelloWorldRust]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d90b5381241b6ccc534a485d2e3466ebf509006"
libc = "musl"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "f950e35b6213b4e519e890f17b90410192e770d5ad2e134f7d7d78d56ef84842"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[HelloWorldRust]]
arch = "i686"
git-tree-sha1 = "6b8717c822bcc6602c1b87c645f1443145a8d6a4"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "d6c7725f92f0873d1418b23a631264d6afce318ca57c26fabe9f56cb8e58d81c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.i686-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "i686"
git-tree-sha1 = "f33a230a277fed5740d73a698bf6545c86eed3d1"
libc = "musl"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "556604973f035360303a4f30f8d6d418be24fb5ba0b5623f8d98f0fa9cfbfd59"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.i686-linux-musl.tar.gz"
[[HelloWorldRust]]
arch = "powerpc64le"
git-tree-sha1 = "7cbfa0f9211bc83bba7aab659e3638588b593dc2"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "692fe4f35c12da8ee8359475a94f475a8d60ee76a15651546ff67221a4b2be66"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "x86_64"
git-tree-sha1 = "8e99971fdedd5d5636f44e7291cc7681f8cdef1a"
os = "macos"

    [[HelloWorldRust.download]]
    sha256 = "11a74dc7a4c6e3c69aee8406228c0a962302a7b72eb1b9b3e4b3a22f48264fda"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.x86_64-apple-darwin.tar.gz"
[[HelloWorldRust]]
arch = "x86_64"
git-tree-sha1 = "e5a585903f05dabc110cb83d3dc9f40a8992f612"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "a2e76a240fa0862e4c963a7695be652ce78d06b72d81ea7b49aa0ae8e86f7ecc"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.x86_64-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "x86_64"
git-tree-sha1 = "03450a8ca8710d422bf01c7e2c2ce6b66e7d1df4"
libc = "musl"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "ba8efc5f2181cb0fa10d8ae250f50d219358619b979e3c04e3b80f75322ab33e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.x86_64-linux-musl.tar.gz"
[[HelloWorldRust]]
arch = "x86_64"
git-tree-sha1 = "179f4bc0644e3515b869c67541e2527b511f8b72"
os = "freebsd"

    [[HelloWorldRust.download]]
    sha256 = "733f499731e7d7642e9fb5e60bb78366f097d288a517b93a574ebfeace3b78e1"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.x86_64-unknown-freebsd.tar.gz"
[[HelloWorldRust]]
arch = "x86_64"
git-tree-sha1 = "dc5b68ea34297f76317cdb46e616e85a67ec38e9"
os = "windows"

    [[HelloWorldRust.download]]
    sha256 = "d8b4c0d556c3fe5d26bb4f454b6189fa88ae4b744d19dab82f247372ac56b9b6"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.1.0+0/HelloWorldRust.v1.1.0.x86_64-w64-mingw32.tar.gz"
