[[HelloWorldRust]]
arch = "aarch64"
git-tree-sha1 = "2c4d326fb48d556f4268fe8c0f7a649aefa2c288"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "38d39b075f41626249fc02491d693de95a236603dcf68d72748688e3fd6ddc6a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.0.0+0/HelloWorldRust.v1.0.0.aarch64-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "i686"
git-tree-sha1 = "e7f74838d039488ad0e815b56e9928d5274cb834"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "e15404d184d37d8132fdc9e6af36d651059466ef115a0258937d9edea6c58f23"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.0.0+0/HelloWorldRust.v1.0.0.i686-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "powerpc64le"
git-tree-sha1 = "3ce9ef5f1e20b4df955adf19c7e938dbac84b8b6"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "643ed0e1cd31e99722989af9f9bd1b2a711d7d83a68b9dbef41b0dad0b3e41ae"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.0.0+0/HelloWorldRust.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[HelloWorldRust]]
arch = "x86_64"
git-tree-sha1 = "47e1e73ff28c0825be3976bc1fb99d988f2c913e"
libc = "glibc"
os = "linux"

    [[HelloWorldRust.download]]
    sha256 = "b094c6e58eb11579ed3ebc7eac51c019e2b12e412e4d9809475f170daedc88f5"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldRust_jll.jl/releases/download/HelloWorldRust-v1.0.0+0/HelloWorldRust.v1.0.0.x86_64-linux-gnu.tar.gz"
